{
    "BENCHMARK_NAME": "fastapi",
    "BUG_NUMBER_START": 1,
    "BUG_NUMBER_END": 16,
    "PYTHON_V": 3.8,
    "TARGET_DIR": "fastapi",
    "TEST_SUITE": ["tests"],
    "EXCLUDE": [],
    "VIRTUAL_ENV": "/home/moe/bugsinpyenv38"
}
  