{
    "BENCHMARK_NAME": "sanic",
    "BUG_NUMBER_START": 1,
    "BUG_NUMBER_END": 5,
    "PYTHON_V": 3.8,
    "TARGET_DIR": "sanic",
    "TEST_SUITE": ["tests"],
    "EXCLUDE": [],
    "VIRTUAL_ENV": "/home/moe/bugsinpyenv38"
}
  