{
    "BENCHMARK_NAME": "luigi",
    "BUG_NUMBER_START": 1,
    "BUG_NUMBER_END": 33,
    "PYTHON_V": 3.8,
    "TARGET_DIR": ".",
    "TEST_SUITE": ["test"],
    "EXCLUDE": ["env", "test"],
    "VIRTUAL_ENV": "/home/moe/bugsinpyenv38"
}
