{
    "BENCHMARK_NAME": "matplotlib",
    "BUG_NUMBER_START": 1,
    "BUG_NUMBER_END": 30,
    "PYTHON_V": 3.8,
    "TARGET_DIR": "lib/matplotlib",
    "TEST_SUITE": ["lib/matplotlib/tests"],
    "EXCLUDE": ["env", "lib/matplotlib/tests"],
    "VIRTUAL_ENV": "/home/moe/bugsinpyenv38"
}
